### ISSUE TITLE
Configuration Issue: Unable to import project into Spring Tools Suite 4

### ISSUE THREAD

**Issue by Zennisch** [kennex666/ForumKnowledge-JavaWWW#5]
### Environment
- Operating System: Windows 11
- Spring Tools Suite 4 version: 4.26.0.RELEASE
- JDK version: 17.0.12

### Steps to Reproduce
1. Clone this repository
2. Open Spring Tools Suite 4
3. Switch workspace into ForumKnowledge-JavaWWW/Workspace
4. File -> Import -> General/Existing Project into Workspace -> Next
5. Select root directory/Browse: ForumKnowledge-JavaWWW\Workspace\Project_ForumKnowledge

### Result
- Error: No projects are found to import

### Screenshot
![image](https://github.com/user-attachments/assets/600d70ac-dec4-422f-a440-a70e524bbe67)

**Comment by kennex666** [comment]
Hi @Zennisch,

Thank you for your report. I will process and update you on this issue as soon as possible. 

Please allow approximately one business day for a response.

Regards,
Kennex

**Comment by kennex666** [comment]
Hi @Zennisch,

Good news! We got your problems. The project can import normally without problems.

Please follow instructions bellow::
1. Clone this repository
2. Open Spring Tools Suite 4
3. Switch workspace into ForumKnowledge-JavaWWW/Workspace
4. File -> Import -> **Select Maven -> Existing Maven Projects** -> Next
5. Select root directory/Browse: ForumKnowledge-JavaWWW\Workspace\Project_ForumKnowledge
6. Select all and click Finish.

Thanks for your issue!
Best,

___

CC contributors: @LeNguyenDuyKhang, @minhbui2003, @EchhOpp
